In [ ]:
import pandas as pd
import numpy as np
np.arange(0,20).reshape(5,4)


#Create DataFrame
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),
            index=["Row1","Row2","Row3","Row4","Row5"],
            columns=["Column1","Column2","Column3","Column4"],
            )

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [47]:
type(df)

pandas.core.frame.DataFrame

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  5 non-null      int64
 1   Column2  5 non-null      int64
 2   Column3  5 non-null      int64
 3   Column4  5 non-null      int64
dtypes: int64(4)
memory usage: 200.0+ bytes


In [49]:
df.describe()

Column1    Column2    Column3    Column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [50]:
#Indexing
#columnname,rowindex[Loc],rowindex columnindex number[.iloc]
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [51]:
df['Column1']

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64

In [44]:
(df[['Column1','Column2','Column3']])

Column1  Column2  Column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10
Row4       12       13       14
Row5       16       17       18

In [52]:
type(df[['Column1','Column2','Column3']])

pandas.core.frame.DataFrame

In [ ]:
df.loc["Row3"]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row2        4        5        6        7

In [58]:
df.loc[["Row3","Row4"]]

Column1  Column2  Column3  Column4
Row3        8        9       10       11
Row4       12       13       14       15

In [59]:
type(df.loc['Row3'])

pandas.core.series.Series

In [60]:
type(df.loc[['Row3','Row4']])

pandas.core.frame.DataFrame

In [61]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [66]:
df.iloc[2:4,0:2]

Column1  Column2
Row3        8        9
Row4       12       13

In [67]:
df.iloc[2:,1:]

Column2  Column3  Column4
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [72]:
#to convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [77]:
##Basic Operation
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [88]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],
            index=["Row1","Row2"],
            columns=["Column1","Column2","Column3"],
            )
print(df)

      Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4


In [82]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [85]:
df[~df.isnull()]

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [89]:
df.isnull()

Column1  Column2  Column3
Row1    False     True    False
Row2    False    False    False

In [91]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [92]:
df['Column2'].value_counts()

Column2
3.0    1
Name: count, dtype: int64

In [93]:
df['Column2'].unique()

array([nan,  3.])

In [94]:
df.loc['Row1'].unique()

array([ 1., nan,  2.])

In [95]:
df>2

Column1  Column2  Column3
Row1    False    False    False
Row2    False     True     True

In [99]:
df<1

False

TypeError: 'int' object is not subscriptable