#Numpy array and bascics

learn about numpy


In [33]:
import numpy as np
##creating array from list
arr_1d=np.array([1,2,3,4,5,6])
print("1D array",arr_1d)
arr_2d=np.array([[1,2,3],[6,7,8]])
print("2D array",arr_2d)


##list vs numpy array
py_list=[1,2,3]
print("Python list multification",py_list*2)


#array multification
np_array=np.array([1,2,3])
print("Python array multification",np_array*2)

#element wise multification
import time
start =time.time()#second time
py_list=[i*2 for i in range(1000000)]
print("\n List Operation time:",time.time() -start)

start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy Operation time:",time.time()-start)

1D array [1 2 3 4 5 6]
2D array [[1 2 3]
 [6 7 8]]
Python list multification [1, 2, 3, 1, 2, 3]
Python array multification [2 4 6]

 List Operation time: 0.035117149353027344

 Numpy Operation time: 0.0021331310272216797


In [36]:
import numpy as np

zeros =np.zeros((3,4))
print("zeros array:",zeros)

ones =np.ones((4,2))
print("ones array:",ones)

full=np.full((2,2),7)
print("Full array:",full)

arrayfull=np.array(full)
print("array list:" ,full*2)

#random method
random=np.random.random((2,3))#random value 0-1
print("random array:",random)

sequence=np.arange(0,15,3)
print("sequence array:",sequence)

zeros array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Full array: [[7 7]
 [7 7]]
array list: [[14 14]
 [14 14]]
random array: [[0.8103202  0.98717616 0.84694291]
 [0.57622447 0.99525145 0.4020985 ]]
sequence array: [ 0  3  6  9 12]


In [2]:
#Vector,Matrix and Tensor
import numpy as np
vector =np.array([1,2,3])
print("vector:",vector)
matrix=np.array([[1,2,3],
                 [4,5,6]])
print("Vector:",matrix)
tensor=np.array([[[1,2],[3,4]],
                 [[5,5],[7,8]]])
print("tensor:",tensor)


vector: [1 2 3]
Vector: [[1 2 3]
 [4 5 6]]
tensor: [[[1 2]
  [3 4]]

 [[5 5]
  [7 8]]]


In [ ]:
#Array properties
arr=np.array([[1,2,3],
              [4,5,6]])
print("shape:",arr.shape)
print("dimension",arr.ndim)
print("Size",arr.size)
print("Dtype:",arr.dtype)

shape: (2, 3)
dimension 2
Size 6
Dtype: int64


In [11]:
#Array Reshaping
arr=np.arange(12)
print("Original array:",arr)

reshaped=arr.reshape((3,4))
print("Reshaped:",reshaped)

flattend=reshaped.flatten()
print("\n Flattened array:",flattend)

#ravel return view instead of copy
raveled=reshaped.ravel()
print("\n Raveled array:",raveled)

#Transpose
transpose=reshaped.T
print("\n Transposed array:",transpose)






Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
