In [52]:
###Advanced operation with Business examples

#Data structure:[resturant_id,2021,2022,2023,2024]
import numpy as np
import matplotlib.pyplot as plt
sales_data=np.array([
    [1,150000,180000,220000,100000],#Paradise Biryani
    [2,120000,140000,160000,1900000],#Beijin=g Bites
    [3,200000,230000,260000,300000],#Pizza Hub
    [4,180000,210000,2400000,2700000],#Burger Point
    [5,160000,185000,205000,230000]#Chai Point
])
print("====Zomato sales analysis===")
print("\n Sample data for first three resturant",sales_data[:3])




====Zomato sales analysis===

 Sample data for first three resturant [[      1  150000  180000  220000  100000]
 [      2  120000  140000  160000 1900000]
 [      3  200000  230000  260000  300000]]


In [ ]:
#total sales per year
print(np.sum(sales_data,axis=0))
yearly_total=np.sum(sales_data[:, 1:],axis=0)
print(yearly_total)
yearly_total=np.sum(sales_data[:, 1:])
print(yearly_total)

[     15  810000  945000 3245000 5230000]
[ 810000  945000 3245000 5230000]
10230000


In [67]:
#Minimun sales per restaurant
min_sales=np.min(sales_data[:,1:],axis=1)
print(min_sales)

min_sales=np.min(sales_data[:,1:],axis=0)
print(min_sales)

[100000 120000 200000 180000 160000]
[120000 140000 160000 100000]


In [68]:
#Maximum sales per year
max_sales=np.max(sales_data[:,1:],axis=1)
print(max_sales)

max_sales=np.max(sales_data[:,1:],axis=0)
print(max_sales)

[ 220000 1900000  300000 2700000  230000]
[ 200000  230000 2400000 2700000]


In [69]:

#Average sales per year
avg_sales=np.mean(sales_data[:,1:],axis=1)
print(avg_sales)
avg_sales=np.mean(sales_data[:,1:],axis=0)
print(avg_sales)

[ 162500.  580000.  247500. 1372500.  195000.]
[ 162000.  189000.  649000. 1046000.]


In [65]:
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[ 150000  330000  550000  650000]
 [ 120000  260000  420000 2320000]
 [ 200000  430000  690000  990000]
 [ 180000  390000 2790000 5490000]
 [ 160000  345000  550000  780000]]
