##Numpy Array Operation


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing",arr[1:7])
print("with step",arr[1:8:2])
print("Negative indexing",arr[-3])

Basic Slicing [2 3 4 5 6 7]
with step [2 4 6 8]
Negative indexing 8


In [12]:
import numpy as np
arr_2d=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Specific element",arr_2d[1,2])
print("Entire row",arr_2d[1])
print("Entire row",arr_2d[:,1])
print("Entire column",arr_2d[:,2])


Specific element 6
Entire row [4 5 6]
Entire row [2 5 8]
Entire column [3 6 9]


##Sorting


In [18]:
import numpy as np
unsorted=np.array([3,1,4,1,5,9,2,6])
print("sorted array",np.sort(unsorted))
arr_2d_unsorted=np.array([[3,1],
                [1,2],
                [2,3]])
print("Sorted 2D array",np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D array",np.sort(arr_2d_unsorted,axis=1))



sorted array [1 1 2 3 4 5 6 9]
Sorted 2D array [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array [[1 3]
 [1 2]
 [2 3]]


In [20]:
#Filter
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number=numbers[numbers%2==0]
print ("Even number:",even_number)
odd_number=numbers[numbers%2==1]
print ("Odd number:",odd_number)

Even number: [ 2  4  6  8 10]
Odd number: [1 3 5 7 9]


In [24]:
#Filter with Mask
mask=numbers>5
print("Number greather than 5",numbers[mask])

Number greather than 5 [ 6  7  8  9 10]


In [44]:
#Fancy indexing vs np.where()
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print("Np where",numbers[where_result])

condition_array=np.where(numbers>5,numbers*2,numbers)
print(condition_array)

condition_array=np.where(numbers>5,"true","false")
print(condition_array)



[1 3 5]
Np where [ 6  7  8  9 10]
[ 1  2  3  4  5 12 14 16 18 20]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [ ]:
#Adding and removing data

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined=np.concatenate((arr1,arr2))
print(combined)

##Array Compatibilty
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatibility shapes",a.shape==b.shape)


original=np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

withnew_row=np.vstack((original,new_row))
print(original)
print(new_row)

new_col=np.array([[7],[8]])
with_new_col=np.hstack((original,new_col))
print("With new column:",with_new_col)

new_row=np.array([[7],[8]])
with_new_row=np.hstack((new_row,original))
print("With new row:",with_new_row)






[1 2 3 4 5 6]
Compatibility shapes True
[[1 2]
 [3 4]]
[[5 6]]
With new column: [[1 2 7]
 [3 4 8]]
With new row: [[7 1 2]
 [8 3 4]]
